language: node_js
script: echo "do nothing"
deploy:
  provider: s3
  access_key_id:
    secure: "QFbJI8/8VoQF/jL+GAPZ6Q5Q7uwfKLmu/hDoFV+uopwAGQhAi+76A5GdwIrh5TXzVFwxLNA3ADotqJskkbE3zCrfgOji9oM1DuP1JlejtsFPSJ61tzEanNUBi9PSmFSBO0a3IgGc9EDhiTBKXBocIN/EE6zu7wbdkQGzkXy+gqx8RE86R+gV2LzB4XRkSzGCkuJNwXqtj3EIEHILm445GHwBBqj1UOwxdlYnVQMt4ikXYy2GQJWV1mLtZucHQehFnR9O1fGbA5HLvy/nHdXPPB4uTqscZldUHGbzr6CgRJKEb+tadq+2MlcGilJKAPQkfQPt9gwDPWFRWq/8bVueafarvme/3HWSmQAgBPCTOIuth2uWyCComeb6HAfLxw2nowRB1fafrnTS3J+tXplqN07CmzCkjEVwSpUYaiwGwm/aeUK+nN8qxGh15SUt9h4jaGA/7kdERLOR+bvSVnW6fCgATThOrq0c28KXIvOcoMcL+vhGiT/mSd3V4ADPESWZrPjimD5S2fyAkKj8Ru/ZI6X3ELObO0ki6159H7Wq/csW1iPvIr9S4qfE7XQIwsmItxlUWsrTDl55WOMHR6syxLc59WZnEhWJgAFQ5uZ67wrbBRfM7LQ0fEruRUinOdbDjbnahIAGjDoTROuBjWu7CCjseMPWjQMpjzhHfg/Jnmg="
  secret_access_key:
    secure: "JqoqJ2qot89UfG/yMSuzTi7dGX/hzpV/E947eQCr1JIDmu1EEBH0tHy0Rg/V3lHsV6Arqq2nDAHEc15mg05DZ0QaS0pDJh5waASjCMn3mckKiJpluAip7SjsgLj5DAXQfuggPmV+ywKUU5cILux2C+odOiRQo5HyOJIsYLfWGFbMxrdk3Q8i9qI4dcIjA+5ERhGstDWmcPumFAK3FOAxVF6Di6WOSsy/g/yQ6T/dLk7k/5HA87MpXTz0cEe/qw0i6tNQ06kP7hnGDEigUUGd4d4Vn7NUp6vbQ6kUTVrowOPRecjgxQGOY71oAGTxIgk6i7d3kRXDjmtcN27vg0GfQ9GshVF8riooLu9LZrnzcR0lJHO6gnQyfTJmxx18eBL+KHWg1oM4GDzsAYO2fVFKK4kHDHTWbLNpJuuX0TLmXNLwXQcXdKpglvbPI7jadwU0Oy/ifge+KXXRlfvbAu1ZT3hzkARQXypAT5j64lKK0VPk6AUB6QyadzqEvB03EhOEMhxMuFK126TbQDkjLpv1KQJSAEMhK74KCINc1Q2nl1UtmfBNFkzt2koqpygKcidpfpvFPvUN8kZKGuBy71zSpIovzwgxOlXTPSfsCSOK+r9C6thphohjl+NdMac1Hdd0qjgcufK929JjD2tpyKbZ1MnkpS2u3Y3ufa5IUojvkjY="
  bucket: shikumi-zukuri.com
  skip_cleanup: true
  region: ap-northeast-1
  endpoint: s3.amazonaws.com
  on:
    branch: master
